config/routes.rb
Rails.application.routes.draw do
  
  root :to => "customers#index"
      
  resources :customers
  
  resources :licences
  
  resources :identities, only: [:index] do
    collection do
      get 'sign_up'
      get 'login'
      get 'authorisation'
      put 'logout'
    end
  end
  
  namespace :api do
    namespace :v1 do
      resources :feeds
      resources :customers
    end
  end
end

app/models/customer.rb
class Customer
  
  attr_accessor :holdings
  
  include Wisper::Publisher
  
  include Mongoid::Document
  include Mongoid::Timestamps  
  
  field :name, type: String
  field :number, type: String
  field :permit, type: Boolean
  
  embeds_many :links
  
  after_save :publish_save_event
  
  def self.create_it(params)
    c = self.new
    #c.subscribe(EventHandler.new)
    c.name = params[:name]
    c.number = params[:number]
    c.permit = params[:permit]
    c.save!
    c
  end
  
  def self.get_customer(id: nil)
    cust = self.find(id)
    cust.get_holdings
    cust
  end
  
  def update_it(params)
    self.name = params[:name]
    self.number = params[:number] 
    params[:permit] == 'true' ? self.permit = true : self.permit = false
    self.save!
    self 
  end
    
  def get_holdings
    holding_link = self.links.where(rel: :quota_holding).first
    if holding_link
      @holdings = QuotaHolding.new.find_by_link(link: holding_link )
      maintain_links(self_rel: :quota_holding, links: @holdings["_links"])            
    else
      @holdings = QuotaHolding.new.find(customer_number: self.number)    
      maintain_links(self_rel: :quota_holding, links: @holdings["_links"])      
    end
    save
  end
    
  private
  
  def maintain_links(self_rel: nil, links: nil)
    #self.holding_link = links["self"]["href"]
    links.each {|rel,link| add_or_update_links(self_rel: self_rel, rel: rel, link: link)}
  end
  
  def add_or_update_links(self_rel: nil, rel: nil, link: nil)
    rel == "self" ? rel = self_rel : rel.to_sym
    l = self.links.where(rel: rel).first
    if l.nil?
      self.links << Link.create_link({rel: rel, url: link["href"]})
    else
      return if l.url == link["href"]
      l.update_link({rel: rel, url: link["href"]})
    end
  end
  
  def publish_save_event
    publish(:customer_change_event, self)
    
  end
    
  
end

app/models/feed.rb
class Feed
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :last_updated, type: Time
  
  embeds_many :feed_entries
  

  def self.add_to_feed(model)
    feed = Feed.last
    feed = Feed.new if !feed
    feed.last_updated = Time.now
    feed.add_entry(model)
    feed
  end
  
  def add_entry(model)
    ent = self.feed_entries.where(ref: model.id).first
    if !ent
      ent = FeedEntry.new.create_entry(model)
      self.feed_entries << ent
    end
    self.last_updated = Time.now
    self.save
    self
  end
  
end

app/models/feed_entry.rb
class FeedEntry
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :ref, type: BSON::ObjectId
  field :model, type: Symbol

  embedded_in :feed
    
  def create_entry(model)
    self.ref = model.id
    self.model = model.class.to_s.downcase.to_sym
    self    
  end
  
  def model_instance
    self.model.to_s.capitalize.constantize.find(self.ref)
  end
  
end

app/models/link.rb
class Link
  
  include Mongoid::Document
  include Mongoid::Timestamps  
  
  field :rel, type: Symbol
  field :url, type: String
  
  
  embedded_in :customer
  
  def self.create_link(params)
    l = self.new(params)
    l
  end
  
  def update_link(params)
    self.attributes = params
  end
  
end

app/models/user_proxy.rb
class UserProxy
  
  include Wisper::Publisher
  
  include Mongoid::Document
  include Mongoid::Timestamps  
  
  field :name, type: String
  field :email, type: String
  field :access_token, type: Hash
  field :id_token_encoded, type: String
  
  def self.find_or_create(auth: nil, id_token_provided: nil)
    id_token_provided ? up = find_by_user_name(name: auth.id_token["preferrer_username"]) : up = find_by_user_name(name: auth.user["user_name"])
    if up
      up.add_attrs(auth: auth, id_token_provided: id_token_provided)
    else
      up = self.new.add_attrs(auth: auth, id_token_provided: id_token_provided)
    end
    up
  end
    
  def self.find_by_user_name(name: nil, id_token_provided: nil)
    self.where(name: name).first
  end
  
  def add_attrs(auth: nil, id_token_provided: nil)
    if id_token_provided
      name = "preferred_username"
      email = "email_verified"
      key = :id_token
    else
      name = "user_name"
      email = "user_email"
      key = :user
    end
    self.name = auth.send(key)[name]
    self.email = auth.send(key)[email]
    self.access_token = auth.access_token
    self.id_token_encoded = auth.id_token_encoded
    save
    self
  end
    
  
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  
  rescue_from Mongoid::Errors::DocumentNotFound, with: :record_not_found
  rescue_from Mongoid::Errors::Validations, with: :invalid_request
  #rescue_from Exceptions::Standard, :with => :invalid_suspect_profile_parameters
  
  respond_to :json

  def record_not_found
    error(status: :not_found, message: "URL does not represent a resource")
  end
  
  def invalid_request
    error(status: :bad_request, message: "The request is badly formatted")
  end
  
  #def record_not_found
  #  head :not_found
  #end
  
  def error(status = :bad_request, message = nil)
    render 'shared/error'
  end
    
  
    
end

app/controllers/api/v1/feeds_controller.rb
class Api::V1::FeedsController < Api::ApplicationController
  
  def index
    @feed = Feed.first
    respond_to do |f|
      f.json
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user_proxy
  
  before_filter :current_user_proxy
  
  private
  
  def current_user_proxy
    @current_user_proxy ||= UserProxy.find(session[:user_proxy]["proxy_id"]) if session[:user_proxy]    
  end
  
  
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index 
    @customers = Customer.all
    #raise
  end
  
  def new
    @customer = Customer.new
  end
  
  def show
    raise
    @customer = Customer.get_customer(id: params[:id])
  end
  
  def create
    @customer = Customer.create_it(params[:customer])
    @customer.subscribe(EventHandler.new)    
    respond_to do |format|
      if @customer.valid?
        format.html { redirect_to customers_path }
      else
        format.html { render action: "new" }
      end
    end      
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.subscribe(EventHandler.new)
    @customer.update_it(params[:customer])
    respond_to do |format|
      if @customer.valid?
        format.html { redirect_to customers_path }
      else
        format.html { render action: "new" }
      end
    end      
  end
  


end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
  
  def sign_up
    raise
  end
  
  def login
    # Send the Login to the ID Service via a OAuth Redirect
    auth_service = IdentityAdapter.new.authorise_url(host: request.host_with_port)
    redirect_to auth_service
  end
  
  def authorisation
    # Get an access token for the logged_in user from the ID Service using an OAuth /token call
    # Now we need to create an internal "user" by getting the /me
    auth = IdentityAdapter.new.get_access(params: params, host: request.host_with_port)
    #user_proxy = UserProxy.find_or_create(auth: auth, id_token_provided: auth.id_token_provided?)
    session[:user_proxy] = {proxy_id: auth.user_proxy.id.to_s, expires: 10.minutes.from_now}
    redirect_to customers_path
  end
  
  def logout
    auth_logout_service = IdentityAdapter.new.logout_url(user_proxy: @current_user_proxy, host: request.host_with_port)
    session[:user_proxy] = nil
    redirect_to auth_logout_service
  end
  
end

app/controllers/licences_controller.rb
class LicencesController < ApplicationController
  
  def index
    redirect_to "http://licence.local:8012"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/_form.html.erb
<div class='alert alert-info fade in' data-alert='alert'>
   <h3>Customer</h3>
</div>

<%= simple_form_for @customer,  as: 'customer', html: { class: 'form-horizontal' },
  wrapper: :horizontal_form,
  wrapper_mappings: {
    check_boxes: :horizontal_radio_and_checkboxes,
    radio_buttons: :horizontal_radio_and_checkboxes,
    file: :horizontal_file_input,
    boolean: :horizontal_boolean
  } do |f| %>
   <%= f.input :name, label: "Name" %>
   <%= f.input :number, label: "Number" %>   
   <%= f.input :permit, as: :boolean, checked_value: true, unchecked_value: false %>   
   <%= f.button :submit %>
<% end %>

app/views/customers/edit.html.erb
<%= render partial: "form" %>

app/views/customers/index.html.erb
<div class='alert alert-info fade in' data-alert='alert'>
   <h3>Customers</h3>
</div>

<table class="table">
   <thead>
     <tr>
       <th>Name</th>
       <th>Number</th>
       <th>Permit</th>       
       <th>Actions</th>      
     </tr>
   </thead>
   <tbody>
      <% for customer in @customers %>         
         <tr>
            <td>
               <%= link_to customer.name, customer_path(customer)%>
            </td>
            <td><%= customer.number %></td>
            <td><%= customer.permit %></td>            
            <td>
               <%= link_to "Show",  customer_path(customer), class: "btn btn-default"%>
               <%= link_to "Edit",  edit_customer_path(customer), class: "btn btn-default"%>               
            </td>
         </tr>
      <% end %>
   </tbody>
</table>

app/views/customers/new.html.erb
<%= render partial: "form" %>

app/views/customers/show.html.erb
<div class="jumbotron">
   <h3><%= @customer.name %></h3>
</div>


<% for holding in @customer.holdings["holdings"] %>
   Stock Symbol<%= holding["stock_symbol"] %>
   Qty <%= holding["qty"] %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Client" %></title>
    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
<header class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="navbar-inner">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Client Service</a>
        </div>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Customer <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "List", customers_path %></li>
                <li><%= link_to "New", new_customer_path %></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Licences <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Perform", licences_path %></li>
              </ul>
            </li>
          </ul>          
          <ul class="nav navbar-nav navbar-right">
            <% if @current_user_proxy %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= @current_user_proxy.name %> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "logout", logout_identities_path, method: :put %></li>
                </ul>
              </li>            
            <% else %>
              <li><%= link_to 'login', login_identities_path%></li>
              <li><%= link_to 'Sign Up', sign_up_identities_path%></li>
            <% end %>
          </ul>          
      </div>
    </div>
  </header>

<div class="container master-container">
    <ul class="breadcrumb">
      <%= yield :breadcrumb %>
    </ul>

    <% if notice %>
      <div class="alert alert-success fade in" data-alert="alert">
        <a class="close" data-dismiss='alert' href="#">×</a>
        <p><%= notice %></p>
      </div>
    <% end %>

    <%= yield %>
    
  </div>

    
  </body>
</html>